Contests dev
source-academy/cadet-frontend pull request #1675
Opened 2021-03-26 05:14 UTC by kevin9foong

### Description

**Summary of changes** 
Support for contest voting assessments for students to vote for contest entries. 
Implemented through a 'practical' assessment with contest voting question and students can view entries and vote
via the contest votes tab. 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### How to test

I have included snapshot testing for the SideContentContestVotingContainer as well as testing for the Contest Voting question
rendering correctly for submitted and yet-to-be submitted submissions. 
There has also been a test to test that the number of entries is displayed dynamically based on the number of entries passed.

To test manually,  
![image](https://user-images.githubusercontent.com/55353265/112585444-c76a2d00-8e34-11eb-9295-7263e55d137d.png)
Clicking each entry changes the program on the code editor workspace. 

The input fields are disabled when the contest voting submission has been submitted. 
![image](https://user-images.githubusercontent.com/55353265/112585348-9984e880-8e34-11eb-8512-6d520ecbebb7.png)

### Checklist

- [x] I have tested this code
- [x] I have updated the documentation

I have left some documentation regarding the purpose of the container - to separate rendering from API calls etc within the components as necessary.

2021-04-01 20:24 UTC, angelsl requested changes
Thanks for your work!

(Note, I've not yet tested this, only visually inspected the changes.)

2021-04-01 20:24 UTC, angelsl commented on src/commons/assessment/AssessmentTypes.ts
> +};
Please rename this to `ContestEntryAnswer` or something less generic.

2021-04-01 20:24 UTC, angelsl commented on src/commons/assessment/AssessmentTypes.ts
> +  answer: string | number | number[] | ContestVotingSubmission | null;
What is `number[]` for?

2021-04-01 20:24 UTC, angelsl commented on src/commons/assessmentWorkspace/AssessmentWorkspace.tsx
> +    const handleContestEntryClick = (submission_id: number, answer: string) => {
camelCase please.

2021-04-01 20:24 UTC, angelsl commented on src/commons/assessmentWorkspace/AssessmentWorkspace.tsx
> +  userId?: User['userId'];
Why is this added? It's not used anywhere.

2021-04-01 20:24 UTC, angelsl commented on src/commons/assessmentWorkspace/AssessmentWorkspace.tsx
> +  assessmentStatus?: AssessmentStatus;
Please don't add this, just use props.canSave.

2021-04-01 20:24 UTC, angelsl commented on src/commons/assessmentWorkspace/AssessmentWorkspace.tsx
> +            assessmentStatus={props.assessmentStatus}
Just use `props.canSave` instead of this

2021-04-01 20:24 UTC, angelsl commented on src/commons/assessmentWorkspace/AssessmentWorkspaceContainer.ts
> +    )[0].status
As above, this is unnecessary

2021-04-01 20:24 UTC, angelsl commented on src/commons/sideContent/SideContentContestLeaderboard.tsx
> +const contestLeaderboardTooltipContent = <span>View the top-rated contest entries!</span>;
This `span` is unnecessary, the text can be just passed as as string

2021-04-01 20:26 UTC, angelsl submitted a review, later dismissed

2021-04-01 20:26 UTC, angelsl commented on src/commons/sideContent/SideContentContestLeaderboard.tsx
> +        <Tooltip
Please use Tooltip2 instead.

2021-04-01 20:26 UTC, angelsl commented on src/commons/sideContent/SideContentContestVoting.tsx
> +        <Tooltip
Please use Tooltip2 instead.

2021-04-02 08:50 UTC, kevin9foong commented on src/commons/sideContent/SideContentContestVoting.tsx
> +        <Tooltip
resolved

2021-05-15 09:46 UTC, chownces requested changes
The voting tab works. However when testing on the staging deployment, the leaderboard does not seem to display any entries even after the voting has ended. Will check with the team again after they complete the usage documentation for this new feature.

2021-05-15 11:26 UTC, kevin9foong commented on src/commons/assessment/AssessmentTypes.ts
> +  answer: ContestEntestCodeAnswer; //contest entry program to be input into editor
yup indeed...

2021-05-16 06:41 UTC, chownces approved these changes

2021-05-16 18:11 UTC, merged