Achievements: SA2122 cumulative pull request
source-academy/cadet-frontend pull request #1701
Opened 2021-04-16 16:41 UTC by jonas-chow

### Description

This is a very large pull request. Sorry to the person reviewing this...
I have not updated the documentation, but I promise to do that after finals week :)
Here's a summary of major changes and their motivations to help you review:

<ins>**AchievementManualEditor.tsx**</ins>
This is for staff to update the goal progress of manual goals of other users.
- Choose a user
- Choose a goal
- Input the new value goal progress should have
- Send a request to the backend to update the goal progress

Users is filtered to only be the users who are in the staff's group, or all users if the staff does not have a studio group assigned.
_NOTE: I'm not sure how studio is actually represented, but if the representation is consistent throughout the store, then this should work._

<ins>**AchievementEditor.tsx, GoalEditor.tsx**</ins>
- Added call to reverse() so that new achievements/goals appear at the top instead of the bottom.

<ins>**AchievementSettings.tsx**</ins>
- Changed deprecated Tooltip to Tooltip2. This change is present in many files that I may not elaborate on in the future.
- Added changeVariableXp button into the settings. This button toggles the variableXp field of the achievement. More details in AchievementTypes.ts.

<ins>**EditableCard.tsx, EditableCardTypes.ts**</ins>
- Added actions to change xp and variableXp fields in the achievement. This is due to a change in the structure of an achievement.
- Extra logic in changeGoalUuids to add the achievement uuid into the goals so that goals can point back to their implementing achievements.

<ins>**EditableGoalUuids, EditablePrerequisiteUuids**</ins>
- Filter added so that deleted goals are removed from the list of goals. This is done because the provided achievement is just a copy of the original, and removing the goal will not automatically remove the reference in the copy.

<ins>**EditableDate.tsx, EditableTime.tsx**</ins>
Part of EditableEventMeta.tsx.
- Is used to select a date and time for the event listener to determine if it is supposed to increment the counter of that goal.

<ins>**GoalTemplate.ts**</ins>
Just the default Goal Meta provided when creating new Goals.

<ins>**EditableAchievementsMeta, EditableXpMeta, EditableManualMeta.tsx**</ins>
One field to specify the target count to reach for the goal to be considered as completed.

<ins>**EditableAssessmentMeta, EditableBinaryMeta.tsx**</ins>
GoalTypes implemented by the previous achievements team. Leaving it here just in case we want to return to that implementation, or if there are things that we can learn from these.

<ins>**EditableEventMeta.tsx**</ins>
Used for editing Event Type goals. Able to:
- Select the type of event to track
- Add more events to track
- Choose how many times the event should happen
- Choose the start and end date that the event should be tracked (release and deadline)
- Choose the start and end time each day that the event should be tracked (observeFrom and observeTo)

<ins>**AchievementLevel.tsx, AchievementMilestone.tsx**</ins>
- Users start at level 1
- Users are able to hover over the XP bar to see their total XP gained

<ins>**AchievementBackender.ts**</ins>
- Used to cast achievements and goals into the proper structure to be sent to and received from the backend

<ins>**AchievementInferencer.ts**</ins>
- Invalid goals and achievements to represent a failed lookup, instead of returning undefined
- A bunch of little helper functions that are documented in the code itself
- Fake achievements and goals are inserted on the fly and do not get saved into the backend. 
  - Used for inserting achievements and goals for assessments

<ins>**DateHelper.ts**</ins>
- Functions that help to parse dates into strings, or get other useful information about the date

<ins>**InsertFakeAchievements.ts**</ins>
- Called in the achievementDashboard, takes each assessmentOverview and adds fake achievements and goals into the inferencer if needed.
- Results in a nice breakdown of the user's XP earned from assessments

<ins>**AchievementInferencer.test.ts**</ins>
- Updated to conform to the new achievement/goal structure
- Several new tests added

<ins>**eventHandler.ts**</ins>
- The thing that handles the logic for goals to "listen" to events
- processEvent is called whenever an event happens
  - Checks all goals, and increments the count for all eligible goals
  - If the goal is completed, checks its implementing achievements
  - If any achievement is completed, shows a notification
  - Updates the goal progress in the backend
  - If there are no goals in the inferencer, it tries to load the goals and achievements from the store or backend, and tries again
    - If there are still no goals, then there must simply just be no goals and we end the recursion.

<ins>**AchievementViewGoal.tsx**</ins>
- Added a progress bar for each goal for clarity

<ins>**AchievementMocks.ts**</ins>
- Updated to conform to the new achievement/goal structure

<ins>**AchievementSaga.ts, RequestsSaga.ts**</ins>
- Implemented a way to get all the users in the database
- Refactored some of the type casting

<ins>**WorkspaceSaga.ts**</ins>
- Multiple calls to processEvent()

<ins>**AchievementActions.ts, AchievementReducer.ts**</ins>
- Implement actions to get and save users

<ins>**AchievementTypes.ts**</ins>
- Structural changes
  - Achievements now have XP, and a field for variableXp
  - if variableXp is true, the xp earned from the achievement will be the sum of the counts of the achievement's goals
- Motivation: XP should be tied to achievements, and not goals

<ins>**AchievementDashboard.tsx, AchievementDashboardContainer.tsx**</ins>
- Now inserts fake achievements for all assessments
- Also computes if the amount of XP/Achievements gained were able to unlock new achievements
- Has a manual goal editor for staff to edit goal progress manually
- AchievementTasks generated are now only achievements that have been released. Unreleased achievements will not appear.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### How to test

Run this locally with local backend (achievements branch if that pull request hasn't been approved yet).
- Achievement Control will be at localhost:8000/achievement/control
- You can add goals and achievements at will.
- Only able to remove goals and achievements that have been saved in the backend. 
  - Actually it's ok otherwise, just that you'll get some errors logged in your console because you tried to delete a nonexistent entry
- Only able to make the association between goals and achievements that have been saved in the backend. 
  - Due to achievements and goals needing to establish that same association in the backend
  - Just need to make sure to publish changes before you start adding goals or prerequisites into the achievements

To test, just make a goal of each supported type, and make a few achievements too. Click publish changes, then enter the settings of each achievement and give them a few goals each. 

Complete the goals in various ways.
- Manual Goals are completed with the AchievementManualEditor at the top of the achievement dashboard
- Event Goals are mostly completed by running some code in the playground or an assessment
- Achievement and XP goals are completed by visiting the AchievementDashboard
- Assessment and Binary goals are not supported and should not be used

For achievements that complete with event goals, achievement goals, and xp goals, there should be a notification displayed when you receive the achievement.

Submit and grade an assessment to see if that assessment's achievement is added, and its XP is correct.

Feel free to drop me a message on telegram @Trapyon if there's anything unclear or amiss.

 [...]

2021-04-17 10:36 UTC, angelsl requested changes
Overall comments aside from the inline comments:

1. There seems to be quite a lot of mutation of the achievement and goal objects, and if I'm not wrong, those are mutating the objects that are directly in the Redux store.
   
   That is a huge React no-no; it is supposed to be pure functional. This can lead to hard to debug issues because the UI won't rerender when you simply mutate an object like this.

   The changes should be done on a copy of the goal/achievement object. Then shallow copy the list/map of goals/achievements (so we get a new list/map), replace the changed object, and update the Redux store with the changed list/map. The original list/map is unchanged.

2. The updating of achievement and XP goal progress should be done on the backend. The only student-accessible endpoint should be for registering a single event occurrence only. (Or maybe you want to buffer events and update them once in a while only, to reduce the number of requests.

   There should be a separate staff endpoint for updating the progress of manual goals.

2021-04-17 10:36 UTC, angelsl commented on src/commons/achievement/utils/eventHandler.ts
> +        goal.count = goal.count + increment;
Is this mutating the goal object that is in the Redux store?

2021-04-17 10:36 UTC, angelsl commented on src/commons/achievement/utils/eventHandler.ts
> +        goal.completed = true;
Is this mutating the goal object that is in the Redux store?

2021-04-17 10:36 UTC, angelsl commented on src/commons/achievement/control/GoalEditor.tsx
> +        {generateEditableGoals(inferencer.getAllGoalUuids().reverse())}
This seems like it should be memoised..

2021-04-17 10:36 UTC, angelsl commented on src/commons/achievement/control/AchievementEditor.tsx
>                  inferencer.getAchievementPositionByUuid(a) -
The result of generateEditableCards should probably be memoised

2021-04-17 10:36 UTC, angelsl commented on src/commons/achievement/control/achievementEditor/EditableCard.tsx
> +      goal.achievementUuids[len] = uuid;
Mutating the goal in the Redux store?

2021-04-17 10:36 UTC, angelsl commented on src/commons/achievement/utils/AchievementInferencer.ts
> +        : AchievementStatus.UNRELEASED;
This is mutating the achievement in the Redux store..

2021-04-17 10:36 UTC, angelsl commented on src/commons/application/ApplicationTypes.ts
> +  users: []
The list of users is not exactly specific to achievements, but.. sigh.

Since it's only used by achievements, fair enough I guess.

2021-04-17 10:36 UTC, angelsl commented on src/features/achievement/AchievementTypes.ts
> +};
As earlier. This isn't specific to achievements at all, but nevermind for now..

2021-04-17 10:36 UTC, angelsl commented on src/features/achievement/AchievementTypes.ts
> +  users: AchievementUser[];
^

2021-05-20 13:19 UTC, YaleChen299 approved these changes
I have tested the expected behaviours and they all works fine. Staff can add achievements and students can view achievements correctly. One small thing is that the images takes very long to load for the first load. In my opinion, the UI for achievement control can be arranged better to improve the experience. Generally very good work done! Thank you!

2021-05-24 06:56 UTC, merged