Refactor listVisualizer to dataVisualizer and minor fixes
source-academy/cadet-frontend pull request #1703
Opened 2021-04-17 09:56 UTC by VimuthM

### Description

Refactored all instances of ListVisualizer to DataVisualizer to maintain consistency and to represent the tool more accurately.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update
- [X] Code quality improvements

### Checklist

- [X] I have tested this code
- [ ] I have updated the documentation

2021-04-18 03:24 UTC, chownces requested changes
- Bug with Hotkeys. To reproduce: call `draw_data` __once__, and press the left or right arrow keys with the data visualizer tab in focus (the app shld break)
- The scrolling issue on mobile (touch devices) is back again: the tab cannot be scrolled when the scrolling is initiated on a drawn structure
- Currently, the UI is slightly different on the mobile version (as the mobile playground is styled separately)
    - (Need to check again with the Modules team) But I think it would be good if you could separate out the CSS for the dataviz tab, and style it once and for all in the React component (and remove it from the SCSS file)
    - This would also facilitate the eventual possibility of migrating the entire dataviz logic to the new modules system
- I need to double check with the team regarding the new UI for the dataviz tab (I think the single structure call with the new background looks a little weird now)
Ok:
![image](https://user-images.githubusercontent.com/53928333/115133080-07898d80-a038-11eb-859e-4f35a691380b.png)

May look a little weird with the background color, and on its own:
![image](https://user-images.githubusercontent.com/53928333/115133116-60f1bc80-a038-11eb-8459-377fdb34a483.png)

- It would be nice if you could ctrl-f the entire repo and check the spelling of 'visualiser'

2021-04-30 05:27 UTC, martin-henz approved these changes
Looks fine!

2021-04-30 11:01 UTC, VimuthM commented
> * Bug with Hotkeys. To reproduce: call `draw_data` **once**, and press the left or right arrow keys with the data visualizer tab in focus (the app shld break)
@chownces, having some difficulty reproducing this right now. A single call to `draw_data` shouldn't show the left right arrows in the first place...

2021-05-02 13:23 UTC, chownces approved these changes

2021-05-03 03:08 UTC, merged