P2Plus: SourceAcademy Mission Creation Interface
source-academy/cadet-frontend pull request #1762
Opened 2021-06-01 08:55 UTC by ChengGeng97

### Description
Creates a way for GitHub-hosted missions to be created through the Source Academy website.

Subfeatures:
- Ability to create and delete new tasks for a mission
- Ability to create, edit and delete test cases for a mission
- Ability to load test cases

### Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### How to test

### Checklist

- [ ] I have tested this code
- [ ] I have updated the documentation

2021-06-07 02:22 UTC, ChengGeng97 commented
I'm not sure why it's 541 commits. It should only be about 100. Most of those commits should already have been merged in with P2Minus.

2021-06-07 09:08 UTC, ChengGeng97 commented
To my knowledge, Octokit API for creating repositories under an organization does not exist for Javascript, only for Ruby.

2021-06-07 09:16 UTC, martin-henz commented
> I'm not sure why it's 541 commits. It should only be about 100. Most of those commits should already have been merged in with P2Minus.

I think github counts all commits in this branch from the time it was created. This includes all commits that have been merged from the main branch. That explains the number 541, I think. Don't worry about that.

2021-06-07 09:16 UTC, martin-henz commented
> To my knowledge, Octokit API for creating repositories under an organization does not exist for Javascript, only for Ruby.

What is the consequence of this for this project?

2021-06-08 14:09 UTC, chownces requested changes
Some final touchups!

Btw, is it possible to set a correct answer for the MCQ, and have it light up green when selected?

2021-06-08 14:09 UTC, chownces commented on src/commons/sideContent/githubAssessments/SideContentMissionEditor.tsx
> +    );
the calendar UI seems a little off 
![image](https://user-images.githubusercontent.com/53928333/121198678-e9584500-c8a4-11eb-8e92-da7c658e646a.png)

2021-06-10 13:13 UTC, ChengGeng97 commented
> > To my knowledge, Octokit API for creating repositories under an organization does not exist for Javascript, only for Ruby.
> 
> What is the consequence of this for this project?

I will make sure to write about this when updating the documentation.

I will also make an issue to track this issue after the merge. I think this is a problem that can be solved by sending our own GET requests to GitHub, perhaps through a similar microservice that is being used for logging-in right now, but making the change now might be cutting a bit too close to the end of our internship.

2021-06-11 07:41 UTC, chownces approved these changes
Looks good! Rmb to file an issue regarding the creation of repositories under an organization. Thanks.

2021-06-11 07:43 UTC, merged